### ISSUE TITLE
[uncaught application error]: TypeError - str.replaceAll is not a function

### ISSUE THREAD

**Issue by yogiswar1987** [denodrivers/mysql#145]
at escapeString (https://deno.land/x/sql_builder@v1.9.1/util.ts:83:14) at https://deno.land/x/sql_builder@v1.9.1/util.ts:43:20 at String.replace (<anonymous>) at replaceParams (https://deno.land/x/sql_builder@v1.9.1/util.ts:4:13) at buildQuery (https://deno.land/x/mysql@v2.11.0/src/packets/builders/query.ts:6:23) at PoolConnection.execute (https://deno.land/x/mysql@v2.11.0/src/connection.ts:268:18) at PoolConnection.query (https://deno.land/x/mysql@v2.11.0/src/connection.ts:242:31) at https://deno.land/x/mysql@v2.11.0/src/client.ts:86:31 at Client.useConnection (https://deno.land/x/mysql@v2.11.0/src/client.ts:107:20) at async Client.query (https://deno.land/x/mysql@v2.11.0/src/client.ts:85:12)

**query:** select * from students s s.category_id=? and s.id not in ? `,["0",[2,3,4,5]]);

**Comment by yogiswar1987** [comment]
not an issue
