### ISSUE TITLE
query always returns  empty array

### ISSUE THREAD

**Issue by timreichen** [denodrivers/mysql#29]
```ts
const users = await client.query(`SELECT * FROM users`)
```

**expected behavior**
returns array of objects with data from database.

**actual behavior**
returns an empty array.

**server info**
innodb_version: 5.6.45-86.1
protocol_version: 10
version: 10.1.43-MariaDB

The test database has actual data stored, works with other clients.
I logged some received data in connection.ts. Looks like the field names are received but not the values.

**Comment by magichim** [comment]
Do you execute test.ts code?

If you do it, your local database might have a test database and users table. and the you can watch one record.

Try to type 'deno -A test.ts'

:)

**Comment by timreichen** [comment]
Yeah I did.
Getting following console output (like the other issue I posted):
```
NFO connecting 127.0.0.1:3306
INFO connected to 127.0.0.1
error: Uncaught Error: Got packets out of order
► connection.ts:113:17
113           throw new Error(error.message);
    at nextPacket (connection.ts:113:17)
```

**Comment by manyuanrong** [comment]
The mysql protocol is slightly different in different versions, and the compatibility work makes me tired, which requires a long investment. This is a bit difficult for me, and I need more help. Or should I consider using Rust's mature client instead of writing from scratch

**Comment by timreichen** [comment]
I think a typescript implementation would be best. where can i find the different version specs? Which version did you implement?

**Comment by manyuanrong** [comment]
deno_mysql is not very compatible with MariaDB at the moment, you can try MariaDB 10.2 and above

**Comment by timreichen** [comment]
Looks like the bug comes from the this.lessThan57 method.
the version can have a weird format like "5.5.5-10.1.43-MariaDB"
So I could fix it by adding that line:
```ts
if (segments[2] === "MariaDB") return segments[1] < "5.7.0"
```
This is just a patch. There might be a better way of version detection.

**Comment by TradeIdeasPhilip** [comment]
I think I'm looking at the same bug.

I'm running with the latest version of Deno, 1.4.6.  I get the same results with Deno running on Windows 10 and on Fedora.  

I make a very simple query.  I send to three different databases.  Two of them work as expected.  The third will return an empty list the first time I run the query.  When I run the same query a second time I get a bunch of rows which all say `{null: null}`.

The databases that work are `5.5.39-MariaDB-log MariaDB Server` and `5.5.5-10.2.19-MariaDB MariaDB Server`.  The database that does not work is `5.5.5-10.0.19-MariaDB MariaDB Server`.

These databases all contain identical data managed by MySQL replication.  We've been using these databases in production with C++ clients for years with no issues.  And I can run the query on the MySQL command prompt, so I know the data is there.

Test code and the results:
```
// I'm having trouble accessing some databases, while others work fine.  This seems to be related to
// https://github.com/manyuanrong/deno_mysql/issues/29

import { Client, ClientConfig } from "https://deno.land/x/mysql/mod.ts";

// The following line causes a problem.  Things run like normal at first, but at the end the program would hang.
// More info:  https://github.com/manyuanrong/deno_mysql/issues/60#issuecomment-714828978
//import { Client, ClientConfig } from "https://github.com/manyuanrong/deno_mysql/raw/00d4651316a66b7cb7d98625380c98098556a26b/mod.ts";

function getServerName(): string {
  let serverList = Deno.args;
  if (serverList.length == 0) {
    serverList = ["its-the-cops", "race-condition", "malfunctioning-eddie"];
  }
  const index = Math.floor(Math.random() * serverList.length);
  return serverList[index];
}

async function getClient(): Promise<Client> {
  const config: ClientConfig = {
    hostname: getServerName(),
    username: "web_client",
    password: "NeverSayDie!",
    db: "mydb",
  };
  console.log("config", config);
  const client = await new Client().connect(config);
  return client;
}

async function getData(client: Client) {
  const sql =
    "SELECT start_time AS time FROM bars_1m WHERE symbol = ?  ORDER BY time DESC LIMIT 500";
  const args = ["ORCL"];
  const databaseResult: any[] = await client.query(sql, args);
  if (databaseResult.length <= 10) {
    console.log("full databaseResult", databaseResult);
  } else {
    console.log(
      "databaseResult.length",
      databaseResult.length,
      "start",
      databaseResult.slice(0, 5),
      "end",
      databaseResult.slice(databaseResult.length - 5),
    );
  }
}

async function test() {
  const client = await getClient();
  // On malfunctioning-eddie this first one returns an empty list.
  await getData(client);
  // On malfunctioning-eddie this second one returns a lot of nulls.
  await getData(client);
  // Full results are shown below.
}

test();

// Server version info:

// [phil@joey-mousepad overnight]$ mysql -uweb_client -p'NeverSayDie!' -h its-the-cops
// mysql: [Warning] Using a password on the command line interface can be insecure.
// Welcome to the MySQL monitor.  Commands end with ; or \g.
// Your MySQL connection id is 1298638
// Server version: 5.5.39-MariaDB-log MariaDB Server

// Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

// Oracle is a registered trademark of Oracle Corporation and/or its
// affiliates. Other names may be trademarks of their respective
// owners.

// Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

// mysql> ^DBye
// [phil@joey-mousepad overnight]$ mysql -uweb_client -p'NeverSayDie!' -h race-condition
// mysql: [Warning] Using a password on the command line interface can be insecure.
// Welcome to the MySQL monitor.  Commands end with ; or \g.
// Your MySQL connection id is 310271
// Server version: 5.5.5-10.2.19-MariaDB MariaDB Server

// Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

// Oracle is a registered trademark of Oracle Corporation and/or its
// affiliates. Other names may be trademarks of their respective
// owners.

// Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

// mysql> ^DBye
// [phil@joey-mousepad overnight]$ mysql -uweb_client -p'NeverSayDie!' -h malfunctioning-eddie
// mysql: [Warning] Using a password on the command line interface can be insecure.
// Welcome to the MySQL monitor.  Commands end with ; or \g.
// Your MySQL connection id is 14794723
// Server version: 5.5.5-10.0.19-MariaDB MariaDB Server

// Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

// Oracle is a registered trademark of Oracle Corporation and/or its
// affiliates. Other names may be trademarks of their respective
// owners.

// Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

// mysql>

// Results.  The first two are exactly as expected, the thrid is clearly wrong.

// [phil@joey-mousepad overnight]$ deno run --allow-net DatabaseTest.ts its-the-cops
// Check file:///home/phil/cpp_alert_server/deno/overnight/DatabaseTest.ts
// config {
//   hostname: "its-the-cops",
//   username: "web_client",
//   password: "NeverSayDie!",
//   db: "mydb"
// }
// INFO connecting its-the-cops:3306
// INFO connected to its-the-cops
// databaseResult.length 500 start [
//   { time: 2020-10-21T19:59:00.000Z },
//   { time: 2020-10-21T19:58:00.000Z },
//   { time: 2020-10-21T19:57:00.000Z },
//   { time: 2020-10-21T19:56:00.000Z },
//   { time: 2020-10-21T19:55:00.000Z }
// ] end [
//   { time: 2020-10-20T18:14:00.000Z },
//   { time: 2020-10-20T18:13:00.000Z },
//   { time: 2020-10-20T18:12:00.000Z },
//   { time: 2020-10-20T18:11:00.000Z },
//   { time: 2020-10-20T18:10:00.000Z }
// ]
// databaseResult.length 500 start [
//   { time: 2020-10-21T19:59:00.000Z },
//   { time: 2020-10-21T19:58:00.000Z },
//   { time: 2020-10-21T19:57:00.000Z },
//   { time: 2020-10-21T19:56:00.000Z },
//   { time: 2020-10-21T19:55:00.000Z }
// ] end [
//   { time: 2020-10-20T18:14:00.000Z },
//   { time: 2020-10-20T18:13:00.000Z },
//   { time: 2020-10-20T18:12:00.000Z },
//   { time: 2020-10-20T18:11:00.000Z },
//   { time: 2020-10-20T18:10:00.000Z }
// ]
// [phil@joey-mousepad overnight]$ deno run --allow-net DatabaseTest.ts race-condition
// config {
//   hostname: "race-condition",
//   username: "web_client",
//   password: "NeverSayDie!",
//   db: "mydb"
// }
// INFO connecting race-condition:3306
// INFO connected to race-condition
// databaseResult.length 500 start [
//   { time: 2020-10-21T19:59:00.000Z },
//   { time: 2020-10-21T19:58:00.000Z },
//   { time: 2020-10-21T19:57:00.000Z },
//   { time: 2020-10-21T19:56:00.000Z },
//   { time: 2020-10-21T19:55:00.000Z }
// ] end [
//   { time: 2020-10-20T18:14:00.000Z },
//   { time: 2020-10-20T18:13:00.000Z },
//   { time: 2020-10-20T18:12:00.000Z },
//   { time: 2020-10-20T18:11:00.000Z },
//   { time: 2020-10-20T18:10:00.000Z }
// ]
// databaseResult.length 500 start [
//   { time: 2020-10-21T19:59:00.000Z },
//   { time: 2020-10-21T19:58:00.000Z },
//   { time: 2020-10-21T19:57:00.000Z },
//   { time: 2020-10-21T19:56:00.000Z },
//   { time: 2020-10-21T19:55:00.000Z }
// ] end [
//   { time: 2020-10-20T18:14:00.000Z },
//   { time: 2020-10-20T18:13:00.000Z },
//   { time: 2020-10-20T18:12:00.000Z },
//   { time: 2020-10-20T18:11:00.000Z },
//   { time: 2020-10-20T18:10:00.000Z }
// ]
// [phil@joey-mousepad overnight]$ deno run --allow-net DatabaseTest.ts malfunctioning-eddie
// config {
//   hostname: "malfunctioning-eddie",
//   username: "web_client",
//   password: "NeverSayDie!",
//   db: "mydb"
// }
// INFO connecting malfunctioning-eddie:3306
// INFO connected to malfunctioning-eddie
// full databaseResult []
// databaseResult.length 480 start [ { null: null }, { null: null }, { null: null }, { null: null }, { null: null } ] end [ { null: null }, { null: null }, { null: null }, { null: null }, { null: null } ]
// [phil@joey-mousepad overnight]$ deno --version
// deno 1.4.6
// v8 8.7.220.3
// typescript 4.0.3
// [phil@joey-mousepad overnight]$

// When I ran this in the debugger I could see that the keys were all the string "null" while the values were null.

// I got the previous result on many, many runs.
// One time I saw the following result on the bad machine.
// The database did not shrink.  The number of rows should always be 500.  But that number changes frequently.
// full databaseResult []
// databaseResult.length 222 start [ { null: null }, { null: null }, { null: null }, { null: null }, { null: null } ] end [
//   { null: null },
//   { null: null },
//   {
//     null: "22 08:25:00\x14\x00\x00\x17\x132020-10-22 08:24:00\x14\x00\x00\x18\x132020-"
//   },
//   { null: null },
//   { null: null }
// ]
```

**Comment by TradeIdeasPhilip** [comment]
I found some more servers.  I had to modify my test program slightly, but it's similar to what's above.  I was importing from `https://github.com/manyuanrong/deno_mysql/raw/00d4651316a66b7cb7d98625380c98098556a26b/mod.ts`

Two new servers failed in the same way.  They returned an empty list when I know the result should not have been empty.

Another server failed in a different way.  It threw an exception.

Most of the servers responded with no issues.  This was 100% repeatable.

I've listed all the output below.  Please let me know if you need anything else.

```json
{
  status: "Bad",
  serverName: "malfunctioning-eddie",
  version: [
    [ "innodb_version", "5.6.23-72.1" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.0.19-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ]
  ]
}
{
  status: "Bad",
  serverName: "clamps",
  version: [
    [ "innodb_version", "5.6.36-82.0" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.1.24-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system jemalloc" ],
    [ "version_ssl_library", "OpenSSL 1.0.2k-fips  26 Jan 2017" ],
    [ "wsrep_patch_version", "wsrep_25.19" ]
  ]
}
{
  status: "Bad",
  serverName: "id-10-t",
  version: [
    [ "innodb_version", "5.6.39-83.1" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.1.33-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system jemalloc" ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Bad",
  serverName: "wally-balls",
  version: [
    [ "protocol_version", "10" ],
    [ "version", "5.1.51-log" ],
    [ "version_comment", "MySQL Community Server (GPL) by Remi" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "redhat-linux-gnu" ]
  ],
  exception: "Error: ndshake\n    at PoolConnection.nextPacket (connection.ts:143:13)\n    at async PoolConnection._..."
}
{
  status: "Good",
  serverName: "flexo",
  version: [
    [ "innodb_version", "1.1.8" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "5.5.18-log" ],
    [ "version_comment", "MySQL Community Server (GPL)" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ]
  ]
}
{
  status: "Good",
  serverName: "calculon",
  version: [
    [ "innodb_version", "5.5.35-MariaDB-33.0" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "5.5.35-MariaDB-log" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ]
  ]
}
{
  status: "Good",
  serverName: "its-the-cops",
  version: [
    [ "innodb_version", "5.5.38-MariaDB-35.2" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "5.5.39-MariaDB-log" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ]
  ]
}
{
  status: "Good",
  serverName: "null-pointer",
  version: [
    [ "innodb_version", "5.5.59-MariaDB-38.11" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "5.5.60-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ]
  ]
}
{
  status: "Good",
  serverName: "bender",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "crushinator",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "dirty-laundry",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "joe-walsh",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "lifes-been-good",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "project-satan",
  version: [
    [ "innodb_version", "5.7.22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.39-83.1" ],
    [ "version", "10.2.16-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0h-fips  27 Mar 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "roberto",
  version: [
    [ "innodb_version", "5.7.22-22" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tls_version", "TLSv1,TLSv1.1,TLSv1.2" ],
    [ "version", "5.7.22-22" ],
    [ "version_comment", "Percona Server (GPL), Release 22, Revision f62d93c" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_suffix", "" ]
  ]
}
{
  status: "Good",
  serverName: "race-condition",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.19-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "hotel-california",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.21-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "izac",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.21-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "monique",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.21-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "nurse-ratchet",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.21-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "parts-hilton",
  version: [
    [ "innodb_version", "5.7.24" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "version", "10.2.21-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [ "version_malloc_library", "system" ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.23" ]
  ]
}
{
  status: "Good",
  serverName: "angleyne",
  version: [
    [ "innodb_version", "5.7.25" ],
    [ "protocol_version", "10" ],
    [ "slave_type_conversions", "" ],
    [ "tokudb_version", "5.6.41-84.1" ],
    [ "version", "10.2.22-MariaDB" ],
    [ "version_comment", "MariaDB Server" ],
    [ "version_compile_machine", "x86_64" ],
    [ "version_compile_os", "Linux" ],
    [
      "version_malloc_library",
      "jemalloc 5.0.1-0-g896ed3a8b3f41998d4fb4d625d30ac63ef2d51fb"
    ],
    [ "version_ssl_library", "OpenSSL 1.1.0i-fips  14 Aug 2018" ],
    [ "wsrep_patch_version", "wsrep_25.24" ]
  ]
}
```

**Comment by timreichen** [comment]
Closing this because of inactivity. Not sure, I don't know if the bug is fixed. Else feel free to reopen.
