### ISSUE TITLE
Compilation fails with deno@v1.5.x

### ISSUE THREAD

**Issue by uki00a** [denodrivers/mysql#93]
## Summary

When trying to use `deno-mysql@v2.5.0` from `deno@v1.5.1`, it fails to compile with the following message:

```shell
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { LogLevels, LevelName } from "./levels.ts";
                    ~~~~~~~~~
    at https://deno.land/std@0.63.0/log/mod.ts:13:21

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Deferred,
  ~~~~~~~~
    at https://deno.land/x/mysql@v2.5.0/deps.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Client, ClientConfig } from "./src/client.ts";
                 ~~~~~~~~~~~~
    at https://deno.land/x/mysql@v2.5.0/mod.ts:1:18

Found 3 errors.
```

## Steps to reproduce

```typescript
// sample.ts
import { Client } from "https://deno.land/x/mysql@v2.5.0/mod.ts";

const client = new Client();
client.connect({
  hostname: "localhost",
  port: 3306,
  username: "test",
  db: "test",
  password: "test",
});
console.log(await client.query(`SELECT 1`));
await client.close();
```

```shell
$ deno run --allow-net ./sample.ts
```

## Environment

```
$ deno --version
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
```

**Comment by uki00a** [comment]
Testing in the master branch of `deno_mysql`, it compiles successfully. It seems to have been fixed at #91 :smiley: 

@manyuanrong Could you please release new version of deno_mysql when you are free?

**Comment by lideming** [comment]
I just released a new version 😄

**Comment by uki00a** [comment]
Resolved, thanks a lot @lideming!

**Comment by Kennytian** [comment]
- Using default version: import { Client } from "https://deno.land/x/mysql/mod.ts";

```
error: TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Deferred,
  ~~~~~~~~
    at https://deno.land/x/mysql/deps.ts:3:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { Client, ClientConfig } from "./src/client.ts";
                 ~~~~~~~~~~~~
    at https://deno.land/x/mysql/mod.ts:1:18

Found 2 errors.

```

---

-  Using latest version: import { Client } from "https://deno.land/x/mysql@v2.6.0/mod.ts";

```
warning: Compiled module not found "https://deno.land/x/checksum@1.4.0/mod.ts"
  From: https://deno.land/x/mysql@v2.6.0/deps.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Compiled module not found "https://deno.land/x/sha256@v1.0.2/mod.ts"
  From: https://deno.land/x/mysql@v2.6.0/deps.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/checksum@1.4.0/mod.ts' does not provide an export named 'Hash'

```


---

-  Using master branch url:   import { Client } from "https://raw.githubusercontent.com/denodrivers/mysql/master/mod.ts";

```
warning: Compiled module not found "https://deno.land/x/checksum@1.4.0/mod.ts"
  From: https://raw.githubusercontent.com/denodrivers/mysql/master/deps.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
warning: Compiled module not found "https://deno.land/x/sha256@v1.0.2/mod.ts"
  From: https://raw.githubusercontent.com/denodrivers/mysql/master/deps.ts
    If the source module contains only types, use `import type` and `export type` to import it instead.
error: Uncaught SyntaxError: The requested module 'https://deno.land/x/checksum@1.4.0/mod.ts' does not provide an export named 'Hash'
```

Env:
```
deno --version
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
```

@lideming @uki00a

**Comment by lideming** [comment]
@Kennytian 
Can't reproduce. It works on CI (https://github.com/lideming/deno_mysql/runs/1339875462). 🤔

The "Compiled module not found" error is weird. It's from https://github.com/denoland/deno/blob/6844caa9a552e3f8fd1f2139bdffdd090d48fe9a/cli/program_state.rs#L223
I think there is possibly some broken module cache.

**Comment by Kennytian** [comment]
@lideming  Nick guy, thanks for your quickly response.

Run 
```
deno cache -r https://deno.land/x/mysql/mod.ts 
deno cache -r https://deno.land/x/mysql/deps.ts
```
it's work for me!
